@startuml

'Rectilinear layout :
skinparam linetype ortho

entity Machine {
* id: int
___
idOperationEffectuee:int
idPosteDeTravail:int
idEtatMachine: int
reference: varchar
description: text
puissance: double
coutHoraire: double
}

entity Type0peration{
* id: int
___
description: text
}

entity Produit {
* id: int
___
idGamme : int
idExemplaire:int
___
reference: varchar
description: text
}

entity Machine_TypeOperation {
* idMachine: int
* idTypeOperation : int
___
duree: double
}

Machine <-- Machine_TypeOperation
Type0peration <-- Machine_TypeOperation

entity Gamme {
* id : int
___
reference: varchar
description: text
}

Produit --> Gamme : plan de fabrication

entity Operation {
* id: int
___
idTypeOperation : int
___
debutOperation: double
finOperation: double
}

Operation --> Type0peration

entity Gamme_Operation {
*idOperation: int
*idGamme: int
idOperationEffectuee: int
}

Operation <-- Gamme_Operation
Gamme <-- Gamme_Operation

entity Operation_Ordre {
*idOperationAmont: int
*idOperationAval: int
}

Operation_Ordre --> Operation
Operation_Ordre --> Operation

entity Exemplaire {
* id: int
___
reference: varchar
numeroDeSerie: varchar
}

Produit <-- Exemplaire

entity OperationEffectuee {
* id: int
___
debutOperation: double
finOperation: double
}

Operation <-- OperationEffectuee
OperationEffectuee --> Machine

entity PosteDeTravail {
*id: int
___
description:text
positionX: int
positionY: int
}

entity Operateur {
* id: int
___
idEtatOperateur: int
nom: varchar
prenom: varchar
}

entity Operateur_PosteDeTravail {
*idOperateur: int
*idPosteDeTravail: int
idHabiliteATravaillerSur: int
}

Operateur <--Operateur_PosteDeTravail
PosteDeTravail <-- Operateur_PosteDeTravail

PosteDeTravail <-- Machine

entity EtatMachine {
* id: int
___
nom: varchar
}

EtatMachine <-- Machine

entity EtatOperateur {
* id: int
nom: varchar
}

EtatOperateur <-- Operateur


@enduml